config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'books#index'
  concern :commentable do
    resources :comments
  end
  resources :books, concerns: :commentable
  resources :reports, concerns: :commentable
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: %i[show index] do
    resource :relationships, only: %i[create destroy]
    scope module: :users do
      resources :followings, only: [:index]
      resources :followers, only: [:index]
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[github]

  has_one_attached :image

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id, dependent: :destroy, inverse_of: :following
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy, inverse_of: :follower
  has_many :followers, through: :passive_relationships, source: :following

  has_many :reports, dependent: :destroy

  has_many :books, dependent: :destroy

  has_many :comments, dependent: :destroy

  validates :name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.nickname
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def follow(user)
    return if id == user.id

    follow = active_relationships.build(follower_id: user.id)
    follow.save
  end

  def unfollow(user)
    follow = active_relationships.find_by(follower_id: user.id)
    follow.destroy
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/users/followers_controller.rb
# frozen_string_literal: true

module Users
  class FollowersController < ApplicationController
    PAGE_MAX_USER = 10
    def index
      user = User.find(params[:user_id])
      @followers = user.followers.page(params[:page]).per(PAGE_MAX_USER)
    end
  end
end

app/controllers/users/followings_controller.rb
# frozen_string_literal: true

module Users
  class FollowingsController < ApplicationController
    PAGE_MAX_USER = 10
    def index
      user = User.find(params[:user_id])
      @followings = user.followings.page(params[:page]).per(PAGE_MAX_USER)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def github
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
      else
        session['devise.github_data'] = request.env['omniauth.auth'].except('extra')
        redirect_to new_user_registration_url
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    def build_resource(hash = {})
      hash[:uid] = User.create_unique_string
      super
    end

    protected

    def update_resource(resource, params)
      if params[:password].present? && params[:password_confirmation].present?
        resource.update(params)
      else
        resource.update_without_password(params)
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user
      render :show
    else
      redirect_to user_path
    end
  end
end

app/views/users/_follow.html.erb
<%= button_to t('users.follow'), user_relationships_path(@user.id), method: :post, remote: true, class: 'follow-btn'%>

app/views/users/_unfollow.html.erb
<%= button_to t('users.unfollow'), user_relationships_path(@user.id), method: :delete, remote: true, class: 'unfollow-btn'%>

app/views/users/_user.html.erb
<p class='user-name'><%= link_to user.name, user_path(user) %></p>

app/views/users/index.html.erb
<h1><%= t('action_link.index', model: User.model_name.human) %></h1>
<%= render @users %>

app/views/users/show.html.erb
<h1><%= t('action_link.show', model: User.model_name.human) %></h1>
<div class="user-profile">
  <% if @user.image.attached? %>
    <%= image_tag @user.image, class: 'user-icon' %>
  <% end %>

  <div class="user-info">
    <div class='user-name'>
      <%= @user.name %>
    </div>
    <div class='user-follow'>
      <div id='follow-btn-box'>
        <% if (current_user != @user) && user_signed_in? %>
          <% if @user.followed_by?(current_user) %>
            <%= render 'users/unfollow' %>
          <% else %>
            <%= render 'users/follow' %>
          <% end %>
        <% end %>
      </div>
      <div class='user-follow-info'>
        <div class='follower-count'>
          <%= link_to user_followers_path(@user) do %> 
            <%= @user.followers.count %><%= t 'users.follower' %>
          <% end %>
        </div>
        <div class='following-count'>
          <%= link_to user_followings_path(@user) do %> 
            <%= @user.followings.count %><%= t 'users.following' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if current_user == @user %>
  <%= link_to t("devise.shared.links.edit"),  edit_user_registration_path, class:"mt-4 btn btn-success" %>
<% end %>