config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'books#index'
  concern :commentable do
    resources :comments
  end
  resources :books, concerns: :commentable
  resources :reports, concerns: :commentable
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: %i[show index] do
    resource :relationships, only: %i[create destroy]
    scope module: :users do
      resources :followings, only: [:index]
      resources :followers, only: [:index]
    end
  end
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  has_many :comments, as: :commentable, dependent: :destroy
  validates :title, presence: true
  validates :memo, presence: true
  paginates_per 5
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @books = Book.all.page(params[:page])
  end

  def show; end

  def new
    @book = Book.new
  end

  def edit; end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      flash[:notice] = t 'flash.create'
      redirect_to @book
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      flash[:notice] = t 'flash.update'
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    flash[:notice] = t 'flash.destroy'
    redirect_to('/books')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :memo, :picture)
  end

  def correct_user
    redirect_to books_path unless current_user == @book.user
  end
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <%= render 'layouts/error_messages', model: form.object %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :memo %>
    <%= form.text_area :memo, class: "form-control", rows: 10 %>
  </div>

  <div class="form-group">
    <%= form.label :picture %>
    <%= form.file_field :picture, class:"form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary mr-3"%>
<% end %>

app/views/books/edit.html.erb
<h1><%= t 'books.edit.title' %></h1>

<%= render 'form', book: @book %>

app/views/books/index.html.erb
<h1><%= t 'books.index.title' %></h1>

<table class="table table-sm table-dark">
  <thead>
    <tr>
      <th><%= t 'books.title' %></th>
      <th><%= t 'books.memo' %></th>
    </tr>
  </thead>
  <tbody>
     <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.memo %></td>
        <td><%= link_to t('action_link.show', model: Book.model_name.human), book %></td>
        <td><%= link_to t('action_link.edit', model: Book.model_name.human), edit_book_path(book) %> </td>
        <td><%= link_to t('action_link.destroy', model: Book.model_name.human), book, method: :delete, data: { confirm: t('books.js.confirm_message') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class = "mb-3">
  <%= paginate @books%>
  <%= page_entries_info @books %>
</div>

<%= link_to t('action_link.new', model: Book.model_name.human), new_book_path %>

<%= link_to t('action_link.index', model: Report.model_name.human), reports_path %>

<%= link_to t('action_link.index', model: User.model_name.human), users_path %>

app/views/books/new.html.erb
<h1><%= t 'books.new.title' %></h1>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<p>
  <strong><%= t 'books.title' %></strong>
  <%= @book.title %>
</p>

<p>
  <strong><%= t 'books.memo' %></strong>
  <%= @book.memo %>
</p>

<% if @book.picture.present? %>
  <strong><%= t 'books.picture' %></strong>
  <%= image_tag(@book.picture_url, class: 'book_picture') %>
<% end %>

<%= link_to t('action_link.index', model: Comment.model_name.human), book_comments_path(@book) %>

<%= link_to t('action_link.edit', model: Book.model_name.human), edit_book_path(@book) %>