config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'books#index'
  concern :commentable do
    resources :comments
  end
  resources :books, concerns: :commentable
  resources :reports, concerns: :commentable
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: %i[show index] do
    resource :relationships, only: %i[create destroy]
    scope module: :users do
      resources :followings, only: [:index]
      resources :followers, only: [:index]
    end
  end
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @reports = Report.all
  end

  def show; end

  def new
    @report = Report.new
  end

  def edit; end

  def create
    @report = current_user.reports.build(report_params)
    if @report.save
      flash[:notice] = t 'flash.create'
      redirect_to @report
    else
      render :new
    end
  end

  def update
    if @report.update(report_params)
      flash[:notice] = t 'flash.update'
      redirect_to @report
    else
      render 'edit'
    end
  end

  def destroy
    @report.destroy
    flash[:notice] = t 'flash.destroy'
    redirect_to reports_path
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:title, :body)
  end

  def correct_user
    report = Report.find(params[:id])
    redirect_to reports_path unless current_user == report.user
  end
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <%= render 'layouts/error_messages', model: form.object %>
  
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", rows: 10 %>
  </div>

  <%= form.submit class: "btn btn-primary mr-3"%>
<% end %>

app/views/reports/edit.html.erb
<h1><%= t 'reports.edit.title' %></h1>
<%= render 'form', report: @report %>

app/views/reports/index.html.erb
<h1><%= t 'reports.index.title' %></h1>
<% @reports.each do |report| %>
  <%= link_to report.title, report_path(report)  %>
<% end %>
<%= link_to t('action_link.new', model: Report.model_name.human), new_report_path, class: 'btn btn-primary' %>

app/views/reports/new.html.erb
<h1><%= t 'reports.new.title' %></h1>
<%= render 'form', report: @report %>

app/views/reports/show.html.erb
<h1><%= t 'reports.show.title' %></h1>
<%= @report.title %>
<%= @report.body %>
<%= link_to t('action_link.destroy', model: Report.model_name.human), report_path(@report), method: :delete %>
<%= link_to t('action_link.edit', model: Report.model_name.human), edit_report_path(@report) %>
<%= link_to t('action_link.index', model: Comment.model_name.human), report_comments_path(@report) %>